# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  template:
    spec:
      containers:
        - name: app-container
          image: myapp:latest
          envFrom:
            - secretRef:
                name: my-app-secret
