pipeline {
    agent any
    
    environment {
        DOCKER_IMAGE = 'nginx-onyeka-app:0.2'
        DOCKERFILE_PATH = 'containerization-orchestration-core-3-step-17/Dockerfile' // Path to your Dockerfile
    }
    
    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/onyeka-hub/darey.io-capstone-projects.git'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    sh "docker build -t ${DOCKER_IMAGE} -f ${DOCKERFILE_PATH} ."
                }
            }
        }       
    }
}