apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-app-prod
  namespace: argocd
spec:
  destination:
    name: ''
    namespace: prod-namespace
    server: 'https://kubernetes.default.svc'
  source:
    path: prod
    repoURL: 'https://git.example.com/my-app.git'
    targetRevision: HEAD
